"""baseline schema

Revision ID: c544b5601674
Revises:
Create Date: 2026-07-23 09:34:54.024896+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'c544b5601674'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_name'), 'knowledge_bases', ['name'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_is_pinned'), 'conversations', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_conversations_knowledge_base_id'), 'conversations', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_conversations_thread_id'), 'conversations', ['thread_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_knowledge_base_id'), 'documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_items_knowledge_base_id'), 'knowledge_items', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_source_type'), 'knowledge_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_knowledge_items_status'), 'knowledge_items', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_items_title'), 'knowledge_items', ['title'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('docs_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('human_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_conversation_id'), 'review_tasks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_table('upload_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('storage_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('bucket_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('client_mime_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('detected_mime_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('part_size', sa.Integer(), nullable=False),
    sa.Column('total_parts', sa.Integer(), nullable=False),
    sa.Column('file_sha256', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('storage_upload_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('completed_parts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('auto_create_document', sa.Boolean(), nullable=False),
    sa.Column('auto_index_on_complete', sa.Boolean(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('processing_error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_tasks_document_id'), 'upload_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_upload_tasks_knowledge_base_id'), 'upload_tasks', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_upload_tasks_processing_status'), 'upload_tasks', ['processing_status'], unique=False)
    op.create_index(op.f('ix_upload_tasks_status'), 'upload_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_upload_tasks_upload_id'), 'upload_tasks', ['upload_id'], unique=True)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_item_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vector_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_knowledge_base_id'), 'chunks', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_chunks_knowledge_item_id'), 'chunks', ['knowledge_item_id'], unique=False)
    op.create_index(op.f('ix_chunks_vector_id'), 'chunks', ['vector_id'], unique=False)
    op.create_table('knowledge_item_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_item_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('review_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_item_reviews_knowledge_item_id'), 'knowledge_item_reviews', ['knowledge_item_id'], unique=False)
    op.create_index(op.f('ix_knowledge_item_reviews_reviewer_type'), 'knowledge_item_reviews', ['reviewer_type'], unique=False)
    op.create_index(op.f('ix_knowledge_item_reviews_status'), 'knowledge_item_reviews', ['status'], unique=False)
    op.create_table('upload_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_task_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('part_size', sa.Integer(), nullable=False),
    sa.Column('part_sha256', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_task_id'], ['upload_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_task_id', 'part_number', name='uq_upload_parts_task_part')
    )
    op.create_index(op.f('ix_upload_parts_part_number'), 'upload_parts', ['part_number'], unique=False)
    op.create_index(op.f('ix_upload_parts_status'), 'upload_parts', ['status'], unique=False)
    op.create_index(op.f('ix_upload_parts_upload_task_id'), 'upload_parts', ['upload_task_id'], unique=False)
    op.create_table('upload_processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_task_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('depends_on_job_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retry_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('claim_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('locked_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(), nullable=True),
    sa.Column('alert_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_job_id'], ['upload_processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['upload_task_id'], ['upload_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_processing_jobs_celery_task_id'), 'upload_processing_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_upload_processing_jobs_claim_token'), 'upload_processing_jobs', ['claim_token'], unique=False)
    op.create_index(op.f('ix_upload_processing_jobs_depends_on_job_id'), 'upload_processing_jobs', ['depends_on_job_id'], unique=False)
    op.create_index(op.f('ix_upload_processing_jobs_document_id'), 'upload_processing_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_upload_processing_jobs_job_type'), 'upload_processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_upload_processing_jobs_lease_expires_at'), 'upload_processing_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_upload_processing_jobs_locked_by'), 'upload_processing_jobs', ['locked_by'], unique=False)
    op.create_index(op.f('ix_upload_processing_jobs_next_run_at'), 'upload_processing_jobs', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_upload_processing_jobs_stage'), 'upload_processing_jobs', ['stage'], unique=False)
    op.create_index(op.f('ix_upload_processing_jobs_status'), 'upload_processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_upload_processing_jobs_upload_task_id'), 'upload_processing_jobs', ['upload_task_id'], unique=False)
    op.create_table('upload_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_task_id', sa.Integer(), nullable=True),
    sa.Column('processing_job_id', sa.Integer(), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('detail_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processing_job_id'], ['upload_processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['upload_task_id'], ['upload_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_audit_logs_actor'), 'upload_audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_upload_audit_logs_event_type'), 'upload_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_upload_audit_logs_level'), 'upload_audit_logs', ['level'], unique=False)
    op.create_index(op.f('ix_upload_audit_logs_processing_job_id'), 'upload_audit_logs', ['processing_job_id'], unique=False)
    op.create_index(op.f('ix_upload_audit_logs_upload_task_id'), 'upload_audit_logs', ['upload_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_audit_logs_upload_task_id'), table_name='upload_audit_logs')
    op.drop_index(op.f('ix_upload_audit_logs_processing_job_id'), table_name='upload_audit_logs')
    op.drop_index(op.f('ix_upload_audit_logs_level'), table_name='upload_audit_logs')
    op.drop_index(op.f('ix_upload_audit_logs_event_type'), table_name='upload_audit_logs')
    op.drop_index(op.f('ix_upload_audit_logs_actor'), table_name='upload_audit_logs')
    op.drop_table('upload_audit_logs')
    op.drop_index(op.f('ix_upload_processing_jobs_upload_task_id'), table_name='upload_processing_jobs')
    op.drop_index(op.f('ix_upload_processing_jobs_status'), table_name='upload_processing_jobs')
    op.drop_index(op.f('ix_upload_processing_jobs_stage'), table_name='upload_processing_jobs')
    op.drop_index(op.f('ix_upload_processing_jobs_next_run_at'), table_name='upload_processing_jobs')
    op.drop_index(op.f('ix_upload_processing_jobs_locked_by'), table_name='upload_processing_jobs')
    op.drop_index(op.f('ix_upload_processing_jobs_lease_expires_at'), table_name='upload_processing_jobs')
    op.drop_index(op.f('ix_upload_processing_jobs_job_type'), table_name='upload_processing_jobs')
    op.drop_index(op.f('ix_upload_processing_jobs_document_id'), table_name='upload_processing_jobs')
    op.drop_index(op.f('ix_upload_processing_jobs_depends_on_job_id'), table_name='upload_processing_jobs')
    op.drop_index(op.f('ix_upload_processing_jobs_claim_token'), table_name='upload_processing_jobs')
    op.drop_index(op.f('ix_upload_processing_jobs_celery_task_id'), table_name='upload_processing_jobs')
    op.drop_table('upload_processing_jobs')
    op.drop_index(op.f('ix_upload_parts_upload_task_id'), table_name='upload_parts')
    op.drop_index(op.f('ix_upload_parts_status'), table_name='upload_parts')
    op.drop_index(op.f('ix_upload_parts_part_number'), table_name='upload_parts')
    op.drop_table('upload_parts')
    op.drop_index(op.f('ix_knowledge_item_reviews_status'), table_name='knowledge_item_reviews')
    op.drop_index(op.f('ix_knowledge_item_reviews_reviewer_type'), table_name='knowledge_item_reviews')
    op.drop_index(op.f('ix_knowledge_item_reviews_knowledge_item_id'), table_name='knowledge_item_reviews')
    op.drop_table('knowledge_item_reviews')
    op.drop_index(op.f('ix_chunks_vector_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_knowledge_item_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_knowledge_base_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_upload_tasks_upload_id'), table_name='upload_tasks')
    op.drop_index(op.f('ix_upload_tasks_status'), table_name='upload_tasks')
    op.drop_index(op.f('ix_upload_tasks_processing_status'), table_name='upload_tasks')
    op.drop_index(op.f('ix_upload_tasks_knowledge_base_id'), table_name='upload_tasks')
    op.drop_index(op.f('ix_upload_tasks_document_id'), table_name='upload_tasks')
    op.drop_table('upload_tasks')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_conversation_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledge_items_title'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_status'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_source_type'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_knowledge_base_id'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_knowledge_base_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_thread_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_knowledge_base_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_pinned'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_knowledge_bases_name'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
